Add install command for `wheel`
`wheel` is required for building `paho-mqtt`.

On a fresh installation of Ubuntu 20.04, installing `sgframework` results in the following error:

```
  ERROR: Command errored out with exit status 1:
   command: /home/mfr/Projects/virtual-can/.direnv/python-3.8.10/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4oqdwr7u/paho-mqtt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4oqdwr7u/paho-mqtt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-swwzebag
       cwd: /tmp/pip-install-4oqdwr7u/paho-mqtt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for paho-mqtt
```

Installing `whell` up front fixes it.